[package]
name = "ww_date_time"
version = "0.1.0"
authors.workspace = true
description = "Date and time types for shrink_wrap"
edition.workspace = true
license.workspace = true

[dependencies]
shrink_wrap.workspace = true
chrono = { version = "0.4", default-features = false, optional = true }
defmt = { version = "1.0", optional = true }

[features]
default = ["std", "chrono"]
std = ["shrink_wrap/std"]
defmt = ["dep:defmt", "shrink_wrap/defmt"]
chrono = ["dep:chrono"]

[dev-dependencies]
hex-literal = "1"