[package]
name = "all_gpio"
version = "0.1.0"
edition = "2024"

[dependencies]
all_gpio_api = { path = "../all_gpio_api" }
wire_weaver = { workspace = true }
wire_weaver_client_common = { workspace = true }
wire_weaver_usb_host = { workspace = true }
ww_client_server = { workspace = true }
ww_gpio = { workspace = true, features = ["std"] }
tokio = { version = "1", features = ["sync", "rt"] }
futures = "0.3"

[features]
usb-tracing = ["wire_weaver_usb_host/usb-tracing"]

[dev-dependencies]
clap = { version = "4.5", features = ["derive"] }
clap-repl = "0.3"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
console = "0.16"
tracing-subscriber = "0.3"
tracing = "0.1"
anyhow = "1"
ww_self = { workspace = true }
