site_name: wire_weaver
repo_name: vhrdtech/wire_weaver
repo_url: https://github.com/vhrdtech/wire_weaver

nav:
  - "index.md"
  - SerDes:
      - "serdes/shrink_wrap.md"
      - "serdes/derive.md"
  - "types.md"
  - API:
      - "api/overview.md"
      - "api/detailed.md"
      - "api/addressing.md"
      - "api/versioning.md"
  - Evolution:
      - "evolution/rules.md"
      - "evolution/checker_tool.md"
  - Standard library:
      - "std_library/overview.md"
      - "std_library/ww_date_time.md"
      - "std_library/ww_version.md"
      - "std_library/ww_numeric.md"
      - "std_library/ww_self.md"
      - "std_library/ww_si.md"
      - "std_library/ww_client_server.md"
      - "std_library/ww_dfu.md"
      - "std_library/ww_can_bus.md"
      - "std_library/ww_log_baremetal.md"
  - Transport protocols:
      - "transport/overview.md"
      - "transport/usb.md"
  - 'MCU with USB template': 'https://github.com/vhrdtech/wire_weaver_template'
  - "dev_tool.md"

theme:
  name: material
  logo: assets/logo-white.png
  icon:
    repo: fontawesome/brands/github
  palette:
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: red
      accent: black
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: red
      accent: black
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
  features:
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.copy
  font: false
copyright: >
  Copyright &copy; 2025 Roman Isaikin
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
watch:
  - .


plugins:
  - search
