# https://github.com/crate-ci/typos/blob/master/docs/reference.md

[files]
extend-exclude = []

[default.extend-identifiers]

[default.extend-words]
## Project-specific acronym
unx = "unx"

[default]
extend-ignore-identifiers-re = []
