[package]
name = "nucleo_h743zi2"
version = "0.1.0"
edition = "2024"

[dependencies]
cortex-m-rt = "0.7"
defmt = "1.0"
defmt-rtt = "1.0" # consider disable-blocking-mode
panic-probe = { version = "1.0", features = ["print-defmt"] }

cortex-m = { version = "0.7", features = ["critical-section-single-core"] }
embassy-stm32 = { version = "0.5.0", features = ["defmt", "stm32h743zi", "unstable-pac", "exti", "time-driver-tim2"] }

embassy-executor = { version = "0.9.1", features = [
    "nightly",
    "arch-cortex-m",
    "executor-thread",
    "executor-interrupt",
    "defmt"
] }
embassy-time = { version = "0.5.0", features = ["defmt", "defmt-timestamp-uptime", "tick-hz-32_768"] }
embassy-sync = { version = "0.7.2", features = ["defmt"] }
embassy-usb = { version = "0.5", features = ["defmt"] }
static_cell = "2.1"

blinky_api = { path = "../../examples/blinky_api", default-features = false }
wire_weaver_usb_embassy = { workspace = true }
wire_weaver_usb_link = { workspace = true, features = ["device", "defmt"] }
wire_weaver = { workspace = true, default-features = false, features = ["defmt"] }
ww_client_server = { workspace = true, default-features = false }

# to solve "can't find crate for test on IntelliJ"
[[bin]]
name = "blinky"
path = "src/bin/blinky.rs"
test = false
doctest = false
bench = false

