[package]
name = "shrink_wrap_core"
edition.workspace = true
authors.workspace = true
version = "0.2.0"
license = "MIT"
repository.workspace = true
description = "shrink_wrap wire format code generator"

[dependencies]
syn = { version = "2.0", features = ["full", "extra-traits"] }
quote = "1.0"
proc-macro2 = "1.0"
