[package]
name = "compare_wire_formats"
version.workspace = true
authors.workspace = true
description.workspace = true
edition.workspace = true

[dependencies]
serde = "1.0"
rmp-serde = "1.3"
bincode = "2.0"
postcard = "1.1"
serde_json = "1.0"
wire_weaver = { path = "../../wire_weaver" }