[package]
name = "blinky_api"
version = "0.1.0"
edition = "2024"

[dependencies]
wire_weaver = { workspace = true }
defmt = { version = "1.0", optional = true }

[features]
std = ["wire_weaver/std"]
defmt = ["wire_weaver/defmt", "dep:defmt"]