[package]
name = "ww_gpio"
version = "0.1.0"
edition.workspace = true
description = "GPIO control data types and remote bridging API"
license.workspace = true
repository.workspace = true

[dependencies]
wire_weaver = { workspace = true, default-features = false }
ww_si = { workspace = true, default-features = false }
defmt = { version = "1.0", optional = true }

[features]
default = ["std"]
std = ["wire_weaver/std", "ww_si/std"]
defmt = ["dep:defmt", "wire_weaver/defmt", "ww_si/defmt"]
