[target.thumbv7em-none-eabihf]
runner = "probe-rs run --chip STM32H725IG"

[build]
target = "thumbv7em-none-eabihf"

[env]
DEFMT_LOG = "debug,nucleo_h743zi2=debug,wire_weaver_usb_embassy=debug" # By default, only error level messages are emitted
DEFMT_RTT_BUFFER_SIZE = "4096" #avoid loosing output if non-blocking, e.g., during init when a lot of output is generated
# Minimize build size
#[unstable]
#build-std = ["core"]
#build-std-features = ["panic_immediate_abort"] # for even smaller size
