[package]
name = "ww_numeric"
version = "0.1.1"
authors.workspace = true
description = "Various numeric types, subtypes, shift-scale"
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
shrink_wrap.workspace = true
defmt = { version = "1.0", optional = true }
serde = { workspace = true, optional = true }

[features]
default = ["std"]
std = ["shrink_wrap/std"]
defmt = ["dep:defmt", "shrink_wrap/defmt"]
serde = ["dep:serde", "shrink_wrap/serde"]
