[package]
name = "ww_counters"
version = "0.1.0"
authors.workspace = true
description = "Event counters API"
edition.workspace = true
license.workspace = true

[dependencies]
wire_weaver.workspace = true
ww_log_bare_metal.workspace = true
defmt = { version = "1.0", optional = true }

[features]
default = ["std"]
std = ["wire_weaver/std"]
defmt = ["dep:defmt", "wire_weaver/defmt"]
