[package]
name = "blinky_evolved"
version = "0.1.0"
edition = "2024"

[dependencies]
blinky_api = { path = "../blinky_api" } # on purpose link to blinky_api here to demonstrate how #[since = ""] works
wire_weaver = { workspace = true }
wire_weaver_client_common = { workspace = true }
wire_weaver_usb_host = { workspace = true }
ww_client_server = { workspace = true }
tokio = { version = "1", features = ["sync", "rt"] }

[features]
usb-tracing = ["wire_weaver_usb_host/usb-tracing"]

[dev-dependencies]
clap = { version = "4.5", features = ["derive"] }
clap-repl = "0.3"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
console = "0.16"
tracing-subscriber = "0.3"
tracing = "0.1"
anyhow = "1"
ww_self = { workspace = true }
