[package]
name = "mcu_qemu"
version = "0.1.0"
edition = "2024"

[dependencies]
cortex-m = "0.7"
cortex-m-rt = "0.7"
cortex-m-semihosting = "0.5"
panic-semihosting = { version = "0.6", features = ["exit"] }

wire_weaver = { path = "../../wire_weaver", default-features = false, features = ["defmt"] }
ww_client_server = { path = "../../ww_stdlib/ww_client_server", default-features = false }
ww_gpio = { path = "../../ww_stdlib/ww_gpio", default-features = false }

# to solve "can't find crate for test on IntelliJ"
[[bin]]
name = "ww_gpio"
path = "src/bin/ww_gpio.rs"
test = false
doctest = false
bench = false
