[package]
name = "ww_uart"
version = "0.1.0"
authors.workspace = true
description = "UART data types and remote bridging API"
edition.workspace = true
license.workspace = true

[dependencies]
wire_weaver.workspace = true
ww_si = { path = "../ww_si", default-features = false }
defmt = { version = "1.0", optional = true }

[features]
default = ["std"]
std = ["wire_weaver/std", "ww_si/std"]
defmt = ["dep:defmt", "wire_weaver/defmt"]
